export const Representations = {
  TEXT: 'TEXT',
  LINK: 'LINK',
  COLOR_VALUE: 'COLOR_VALUE',
  THUMBNAIL: 'THUMBNAIL'
};

export const Elements = {
  BINARY_SELECT: 'BINARY_SELECT',
  DATA_SELECT: 'DATA_SELECT',
  DATA_MULTISELECT: 'DATA_MULTISELECT',
  CREATABLE_SELECT: 'CREATABLE_SELECT',
  TEXTAREA: 'TEXTAREA',
  DEFAULT_INPUT: 'DEFAULT_INPUT',
  FILE_INPUT: 'FILE_INPUT',
  COLOR_PICKER: 'COLOR_PICKER'
};
