/**
 * Config for a string constants of representation and input elements.
 */

export const Representations = {
  TEXT: 'TEXT',
  LINK: 'LINK',
  COLOR_VALUE: 'COLOR_VALUE',
  THUMBNAIL: 'THUMBNAIL'
};

export const Elements = {
  BINARY_SELECT: 'BINARY_SELECT',
  DATA_SELECT: 'DATA_SELECT',
  DATA_MULTISELECT: 'DATA_MULTISELECT',
  DISABLED_INPUT: 'DISABLED_INPUT',
  PARSABLE_IMAGE_INPUT: 'PARSABLE_IMAGE_INPUT',
  THUMB_RESIZE_INPUT: 'THUMB_RESIZE_INPUT',
  PASSWORD_INPUT: 'PASSWORD_INPUT',
  CREATABLE_MULTISELECT: 'CREATABLE_MULTISELECT',
  TEXTAREA: 'TEXTAREA',
  DEFAULT_INPUT: 'DEFAULT_INPUT',
  FILE_INPUT: 'FILE_INPUT',
  COLOR_PICKER: 'COLOR_PICKER',
  IMAGE_INPUT: 'IMAGE_INPUT'
};
