export const FETCH_COLORIZABLEELEMENTS = 'FETCH_COLORIZABLEELEMENTS';
export const CREATE_COLORIZABLEELEMENT = 'CREATE_COLORIZABLEELEMENT';
export const EDIT_COLORIZABLEELEMENT = 'EDIT_COLORIZABLEELEMENT';
export const DELETE_COLORIZABLEELEMENT = 'DELETE_COLORIZABLEELEMENT';
export const COLORIZABLEELEMENT_OPERATION_SUCCESS = 'COLORIZABLEELEMENT_OPERATION_SUCCESS';
export const COLORIZABLEELEMENT_OPERATION_FAILURE = 'COLORIZABLEELEMENT_OPERATION_FAILURE';
