export const FETCH_COLORIZABLES = 'FETCH_COLORIZABLES';
export const CREATE_COLORIZABLE = 'CREATE_COLORIZABLE';
export const EDIT_COLORIZABLE = 'EDIT_COLORIZABLE';
export const DELETE_COLORIZABLE = 'DELETE_COLORIZABLE';
export const COLORIZABLE_OPERATION_SUCCESS = 'COLORIZABLE_OPERATION_SUCCESS';
export const COLORIZABLE_OPERATION_FAILURE = 'COLORIZABLE_OPERATION_FAILURE';
