export const FETCH_CONFIGURATIONS = 'FETCH_CONFIGURATIONS';
export const FETCH_CONFIGURATION_BY_ID = 'FETCH_CONFIGURATION_BY_ID';
export const CREATE_CONFIGURATION = 'CREATE_CONFIGURATION';
export const EDIT_CONFIGURATION = 'EDIT_CONFIGURATION';
export const DELETE_CONFIGURATION = 'DELETE_CONFIGURATION';
export const CONFIGURATION_OPERATION_SUCCESS = 'CONFIGURATION_OPERATION_SUCCESS';
export const CONFIGURATION_OPERATION_FAILURE = 'CONFIGURATION_OPERATION_FAILURE';
