export const FETCH_FONTS = 'FONTS_FETCH_REQUESTED';
export const FETCH_FONTS_NUMBER = 'FETCH_FONTS_NUMBER';
export const CREATE_FONT = 'CREATE_FONT';
export const UPLOAD_FONT = 'UPLOAD_FONT';
export const EDIT_FONT = 'EDIT_FONT';
export const DELETE_FONT = 'DELETE_FONT';
export const FONTS_OPERATION_SUCCESS = 'FONTS_OPERATION_SUCCESS';
export const FONTS_OPERATION_FAILURE = 'FONTS_OPERATION_FAILURE';
