export const FETCH_FONT_FILES= 'FETCH_FONT_FILES_REQUESTED';
export const FETCH_FONT_FILES_NUMBER = 'FETCH_FONT_FILES_NUMBER';
export const CREATE_FONT_FILE = 'CREATE_FONT_FILE';
export const UPLOAD_FONT_FILE = 'UPLOAD_FONT_FILE';
export const EDIT_FONT_FILE = 'EDIT_FONT_FILE';
export const DELETE_FONT_FILE = 'DELETE_FONT_FILE';
export const FONTS_FILE_OPERATION_SUCCESS = 'FONTS_FILE_OPERATION_SUCCESS';
export const FONTS_FILE_OPERATION_FAILURE = 'FONTS_FILE_OPERATION_FAILURE';
