export const FETCH_GRAPHICS_CATEGORIES = 'FETCH_GRAPHICS_CATEGORIES_REQUESTED';
export const FETCH_GRAPHICS_CATEGORIES_BY_ID = 'FETCH_GRAPHICS_CATEGORY_BY_ID';
export const FETCH_GRAPHICS_CATEGORIES_NUMBER = 'FETCH_GRAPHICS_CATEGORIES_NUMBER';
export const CREATE_GRAPHICS_CATEGORIES = 'CREATE_GRAPHICS_CATEGORY';
export const EDIT_GRAPHICS_CATEGORY = 'EDIT_GRAPHICS_CATEGORY';
export const DELETE_GRAPHICS_CATEGORY = 'DELETE_GRAPHICS_CATEGORY';
export const GRAPHICS_CATEGORY_SUCCESS = 'GRAPHICS_CATEGORY_SUCCESS';
export const GRAPHICS_CATEGORY_FAILURE = 'GRAPHICS_CATEGORY_FAILURE';
