export const FETCH_GRAPHICS = 'FETCH_GRAPHICS';
export const FETCH_GRAPHICS_NUMBER = 'FETCH_GRAPHICS_NUMBER';
export const CREATE_GRAPHIC = 'CREATE_GRAPHIC';
export const EDIT_GRAPHIC = 'EDIT_GRAPHIC';
export const DELETE_GRAPHIC = 'DELETE_GRAPHIC';
export const GRAPHIC_OPERATION_SUCCESS = 'GRAPHIC_OPERATION_SUCCESS';
export const GRAPHIC_OPERATION_FAILURE = 'GRAPHIC_OPERATION_FAILURE';
