export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_NUMBER = 'FETCH_PRODUCTS_NUMBER';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_OPERATION_SUCCESS = 'PRODUCT_OPERATION_SUCCESS';
export const PRODUCT_OPERATION_FAILURE = 'PRODUCT_OPERATION_FAILURE';
