export const FETCH_PRODUCTS_CATEGORIES = 'FETCH_PRODUCTS_CATEGORIES_REQUESTED';
export const FETCH_PRODUCTS_CATEGORIES_BY_ID = 'FETCH_PRODUCTS_CATEGORY_BY_ID';
export const FETCH_PRODUCTS_CATEGORIES_NUMBER = 'FETCH_PRODUCTS_CATEGORIES_NUMBER';
export const CREATE_PRODUCTS_CATEGORIES = 'CREATE_PRODUCTS_CATEGORY';
export const EDIT_PRODUCTS_CATEGORY = 'EDIT_PRODUCTS_CATEGORY';
export const DELETE_PRODUCTS_CATEGORY = 'DELETE_PRODUCTS_CATEGORY';
export const PRODUCTS_CATEGORY_SUCCESS = 'PRODUCTS_CATEGORY_SUCCESS';
export const PRODUCTS_CATEGORY_FAILURE = 'PRODUCTS_CATEGORY_FAILURE';
