export const SELECT_ROW = 'SELECT_ROW';
export const SELECT_2TABLE_ROW = 'SELECT_2TABLE_ROW';
export const ENABLE_EDITING = 'ENABLE_EDITING';
export const ENABLE_CREATING = 'ENABLE_CREATING';
export const ENABLE_DEFAULT_STATUS = 'ENABLE_DEFAULT_STATUS';
