export const SELECT_ROW = 'SELECT_ROW';
export const SET_OBJECT_HOLDER_PROPERTY = 'SET_OBJECT_HOLDER_PROPERTY';
export const ENABLE_EDITING = 'ENABLE_EDITING';
export const ENABLE_CONFIRM_DELETE = 'ENABLE_CONFIRM_DELETE';
export const ENABLE_CREATING = 'ENABLE_CREATING';
export const ENABLE_DEFAULT_STATUS = 'ENABLE_DEFAULT_STATUS';
export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const ENABLE_IMPORT_JSON_STATUS = 'ENABLE_IMPORT_JSON_STATUS';
