import PropTypes from 'prop-types';

export const PTypes = {
  title: PropTypes.string.isRequired,
  addNotification: PropTypes.func.isRequired,
  fetchColors: PropTypes.func.isRequired,
  fetchColorgroups: PropTypes.func.isRequired,
  colors: PropTypes.arrayOf(PropTypes.object),
  colorsLoading: PropTypes.bool.isRequired,
  colorgroups: PropTypes.arrayOf(PropTypes.object),
  colorgroupsLoading: PropTypes.bool.isRequired,
  data: PropTypes.arrayOf(PropTypes.any).isRequired,
  errors: PropTypes.arrayOf(PropTypes.string),
  loading: PropTypes.bool.isRequired,
  fetchData: PropTypes.func.isRequired,
  objectHolder: PropTypes.object,
  status: PropTypes.string.isRequired,
  selectRow: PropTypes.func.isRequired,
  enableEditing: PropTypes.func.isRequired,
  enableCreating: PropTypes.func.isRequired,
  enableDefaultStatus: PropTypes.func.isRequired,
  createEntity: PropTypes.func.isRequired,
  editEntity: PropTypes.func.isRequired,
  deleteEntity: PropTypes.func.isRequired,
  createProductsCategory: PropTypes.func.isRequired,
  setEditingObjectProperty: PropTypes.func.isRequired,
  restoreTableState: PropTypes.func.isRequired,
  productsCategories: PropTypes.array.isRequired,
  uploadProductImage: PropTypes.func.isRequired,
  uploadProductThumb: PropTypes.func.isRequired,
  uploadProductLocationMask: PropTypes.func.isRequired,
  uploadProductLocationOverlay: PropTypes.func.isRequired,
  uploadProductLocationImage: PropTypes.func.isRequired,
  fetchProductsCategories: PropTypes.func.isRequired,
  token: PropTypes.string
};
